"""Increase description length in remainder table

Revision ID: 611958b5d236
Revises: 830cf3a26171
Create Date: 2025-06-30 22:16:47.817161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611958b5d236'
down_revision = '830cf3a26171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_remainder', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=225),
               existing_nullable=True)

    with op.batch_alter_table('personal_transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=225),
               existing_nullable=True)

    with op.batch_alter_table('remainder', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=225),
               existing_nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=225),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('remainder', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('personal_transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('personal_remainder', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
